### ISSUE TITLE
Axes legends is trimmed

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/spatialEpisim#23]
Image generated when running a simulation for Crete, Greece.

<img width="88" alt="image" src="https://github.com/ashokkrish/spatialEpisim/assets/410949/7d483efc-c337-4c44-b56c-df4dd0ffafd1">

Can one of you fix this?

**Comment by bryce-carson** [comment]
Where in the application does this image appear? Which plot, specifically?

**Comment by bryce-carson** [comment]
This is related to #11. These output files are joined to create the MP4 video file; I suspect there is a hard-coded resolution somewhere which leads to the cropping issue, and that the misalignment of the axes labels are related to this or something close by in "context," of course. I'm rambling a little, because obviously the issue wouldn't (or shouldn't) be in unrelated code.

**Comment by bryce-carson** [comment]
Necessarily, because we want to fix this in stable, however, the solution will be different and independent from the solution for #7 and #11.

**Comment by bryce-carson** [comment]
https://github.com/ashokkrish/spatialEpisim/blob/1f6bb3fdb30ec9362f0863ee1493b09e672a49f7/R/rasterPlot.R#L122-L124

The size of the image is indeed hard-coded. The resolution of the following image is 768x768.

![GRC_Infected_0011](https://github.com/user-attachments/assets/ebb965be-8d83-48c9-869c-cd9bdee2b54b)

**Comment by ashokkrish** [comment]
Thanks for catching this. We will fix it with an appropriate image resolution.

**Comment by bryce-carson** [comment]
> Thanks for catching this. We will fix it with an appropriate image resolution.

It's best to avoid hard-coding the resolution of the image because we aren't targeting a printer and we don't know the size or pixel density of the user's laptop or desktop computer display.

My plan for the unstable branch is in #11. This will be a user-customizable solution, and we can simply feed a bunch of plot objects into whatever hungry function's mouth is necessary to get images prepared for splide (what is splide? I mention that in #11).

For this, I'm unsure what the exact solution will be, but leaving the decision on resolution to the server when it has some [information from the user's viewport](https://www.w3schools.com/css/css_rwd_viewport.asp) is likely appropriate; rather than using the user's viewport resolution directly, also, I think the standard web design practice is to just choose the full screen width as the maximum width of the image, then enforce [an aspect ratio](https://en.wikipedia.org/wiki/Aspect_ratio_(image)) and leave the height to be determined at run-time. Then the image is automatically scaled down by the user's browser according to the other CSS constraints (see [the box model](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model)).

I'll do a little research first before pushing a fix to stable.

**Comment by bryce-carson** [comment]
@kle6951 and @Toby-exe, this issue in the stable branch is a good candidate for the two of you to work on together. Can you review the code related to this (just search MP4) and read it together, then perhaps do some pair programming to resolve it in stable?

**Comment by bryce-carson** [comment]
@kle6951 and @Toby-exe, pardon me.

Please _do not_ proceed with hacking on this issue.

I have found that some MP4-related code in the software is in the following file.
https://github.com/ashokkrish/spatialEpisim/blob/0b3467b4fab61821ebd3a6f3abbf904cf72d31af/R/rasterSimulation_DA.R#L780-L790

It's not appropriate to work on this file in stable, because it really needs refactoring, so don't bother with the MP4 stuff for now.

@ashokkrish, having discovered this, I think it's inappropriate to proceed with a fix for #23 in stable. I'm unsure why it broken now, if it actually was working before, but I think it may have been broken beforehand without you realizing it. We haven't changed anything that should affect the generation of the plots or the MP4, so really it should've been broken to begin with in stable. Due to the desperate need of a refactor throughout the R/ folder, I don't think it's worth pursuing a fix for #25 in stable, not as the software is now.

**Comment by ashokkrish** [comment]
As you may have noticed we had hard coded  videoDuration <- 15 # in seconds. It was a temporary fix at that for a specific simulation. We could revisit this at some point.

**Comment by bryce-carson** [comment]
> As you may have noticed we had hard coded videoDuration <- 15 # in seconds. It was a temporary fix at that for a specific simulation. We could revisit this at some point.

I have plans in #11 which will be much more robust, and given that won't have the issue of the playback speed or duration that exists in this implementation with a video generated with hard-coded values, it's another argument towards not fixing this issue in stable.

My hope is that the appearance of the plot will simply "fix itself" during the refactor because the erroneous code will be refactored out.

**Comment by bryce-carson** [comment]
1. Study the code which generates the plot with the Haxby colour palette; it comes from "WorldPopViz.R".
2. Look at the plot in the old-stable codebase in the default tab.
3. Create plots using code adapted from that with infections, rather than population counts, data.
4. You'll want to create a series of plots; worry about animating these/creating an MP4 later.

**Comment by bryce-carson** [comment]
@Toby-exe 
@kle6951
